{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6443f1bc-a79e-49ee-a676-9cf26d8350bf",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  error: subprocess-exited-with-error\n",
      "  \n",
      "  python setup.py bdist_wheel did not run successfully.\n",
      "  exit code: 1\n",
      "  \n",
      "  [41 lines of output]\n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  running build_ext\n",
      "  \n",
      "  ================================================================================\n",
      "  ================================================================================\n",
      "  ================================================================================\n",
      "  \n",
      "                     CMake is not installed on your system!\n",
      "  \n",
      "      Or it is possible some broken copy of cmake is installed on your system.\n",
      "      It is unfortunately very common for python package managers to include\n",
      "      broken copies of cmake.  So if the error above this refers to some file\n",
      "      path to a cmake file inside a python or anaconda or miniconda path then you\n",
      "      should delete that broken copy of cmake from your computer.\n",
      "  \n",
      "      Instead, please get an official copy of cmake from one of these known good\n",
      "      sources of an official cmake:\n",
      "          - cmake.org (this is how windows users should get cmake)\n",
      "          - apt install cmake (for Ubuntu or Debian based systems)\n",
      "          - yum install cmake (for Redhat or CenOS based systems)\n",
      "  \n",
      "      On a linux machine you can run `which cmake` to see what cmake you are\n",
      "      actually using.  If it tells you it's some cmake from any kind of python\n",
      "      packager delete it and install an official cmake.\n",
      "  \n",
      "      More generally, cmake is not installed if when you open a terminal window\n",
      "      and type\n",
      "         cmake --version\n",
      "      you get an error.  So you can use that as a very basic test to see if you\n",
      "      have cmake installed.  That is, if cmake --version doesn't run from the\n",
      "      same terminal window from which you are reading this error message, then\n",
      "      you have not installed cmake.  Windows users should take note that they\n",
      "      need to tell the cmake installer to add cmake to their PATH.  Since you\n",
      "      can't run commands that are not in your PATH.  This is how the PATH works\n",
      "      on Linux as well, but failing to add cmake to the PATH is a particularly\n",
      "      common problem on windows and rarely a problem on Linux.\n",
      "  \n",
      "  ================================================================================\n",
      "  ================================================================================\n",
      "  ================================================================================\n",
      "  [end of output]\n",
      "  \n",
      "  note: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "  ERROR: Failed building wheel for dlib\n",
      "ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (dlib)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting face_recognition\n",
      "  Downloading face_recognition-1.3.0-py2.py3-none-any.whl.metadata (21 kB)\n",
      "Collecting face-recognition-models>=0.3.0 (from face_recognition)\n",
      "  Downloading face_recognition_models-0.3.0.tar.gz (100.1 MB)\n",
      "     ---------------------------------------- 0.0/100.1 MB ? eta -:--:--\n",
      "     ---------------------------------------- 0.8/100.1 MB 4.8 MB/s eta 0:00:21\n",
      "      --------------------------------------- 2.1/100.1 MB 5.9 MB/s eta 0:00:17\n",
      "     - -------------------------------------- 3.7/100.1 MB 6.6 MB/s eta 0:00:15\n",
      "     -- ------------------------------------- 5.5/100.1 MB 7.0 MB/s eta 0:00:14\n",
      "     -- ------------------------------------- 7.3/100.1 MB 7.3 MB/s eta 0:00:13\n",
      "     --- ------------------------------------ 9.4/100.1 MB 7.9 MB/s eta 0:00:12\n",
      "     ---- ---------------------------------- 11.0/100.1 MB 7.8 MB/s eta 0:00:12\n",
      "     ---- ---------------------------------- 12.3/100.1 MB 7.9 MB/s eta 0:00:12\n",
      "     ----- --------------------------------- 14.7/100.1 MB 8.2 MB/s eta 0:00:11\n",
      "     ------ -------------------------------- 16.8/100.1 MB 8.3 MB/s eta 0:00:11\n",
      "     ------- ------------------------------- 18.9/100.1 MB 8.4 MB/s eta 0:00:10\n",
      "     -------- ------------------------------ 21.0/100.1 MB 8.6 MB/s eta 0:00:10\n",
      "     -------- ------------------------------ 22.8/100.1 MB 8.7 MB/s eta 0:00:09\n",
      "     --------- ----------------------------- 25.2/100.1 MB 8.8 MB/s eta 0:00:09\n",
      "     ---------- ---------------------------- 27.3/100.1 MB 8.9 MB/s eta 0:00:09\n",
      "     ---------- ---------------------------- 27.8/100.1 MB 8.8 MB/s eta 0:00:09\n",
      "     ----------- --------------------------- 28.8/100.1 MB 8.3 MB/s eta 0:00:09\n",
      "     ----------- --------------------------- 30.7/100.1 MB 8.3 MB/s eta 0:00:09\n",
      "     ------------ -------------------------- 32.5/100.1 MB 8.3 MB/s eta 0:00:09\n",
      "     ------------- ------------------------- 34.1/100.1 MB 8.3 MB/s eta 0:00:08\n",
      "     ------------- ------------------------- 35.7/100.1 MB 8.3 MB/s eta 0:00:08\n",
      "     -------------- ------------------------ 37.7/100.1 MB 8.4 MB/s eta 0:00:08\n",
      "     --------------- ----------------------- 40.1/100.1 MB 8.5 MB/s eta 0:00:08\n",
      "     ---------------- ---------------------- 42.5/100.1 MB 8.6 MB/s eta 0:00:07\n",
      "     ----------------- --------------------- 43.8/100.1 MB 8.6 MB/s eta 0:00:07\n",
      "     ----------------- --------------------- 45.1/100.1 MB 8.5 MB/s eta 0:00:07\n",
      "     ------------------ -------------------- 46.7/100.1 MB 8.4 MB/s eta 0:00:07\n",
      "     ------------------ -------------------- 48.2/100.1 MB 8.4 MB/s eta 0:00:07\n",
      "     ------------------- ------------------- 50.3/100.1 MB 8.4 MB/s eta 0:00:06\n",
      "     -------------------- ------------------ 52.2/100.1 MB 8.4 MB/s eta 0:00:06\n",
      "     --------------------- ----------------- 54.0/100.1 MB 8.5 MB/s eta 0:00:06\n",
      "     --------------------- ----------------- 55.1/100.1 MB 8.3 MB/s eta 0:00:06\n",
      "     ---------------------- ---------------- 56.9/100.1 MB 8.4 MB/s eta 0:00:06\n",
      "     ---------------------- ---------------- 58.5/100.1 MB 8.3 MB/s eta 0:00:06\n",
      "     ----------------------- --------------- 60.6/100.1 MB 8.4 MB/s eta 0:00:05\n",
      "     ------------------------ -------------- 62.7/100.1 MB 8.4 MB/s eta 0:00:05\n",
      "     ------------------------- ------------- 65.0/100.1 MB 8.5 MB/s eta 0:00:05\n",
      "     -------------------------- ------------ 67.6/100.1 MB 8.6 MB/s eta 0:00:04\n",
      "     -------------------------- ------------ 69.2/100.1 MB 8.6 MB/s eta 0:00:04\n",
      "     --------------------------- ----------- 71.8/100.1 MB 8.7 MB/s eta 0:00:04\n",
      "     ---------------------------- ---------- 73.1/100.1 MB 8.7 MB/s eta 0:00:04\n",
      "     ----------------------------- --------- 75.2/100.1 MB 8.6 MB/s eta 0:00:03\n",
      "     ------------------------------ -------- 77.1/100.1 MB 8.7 MB/s eta 0:00:03\n",
      "     ------------------------------ -------- 78.9/100.1 MB 8.6 MB/s eta 0:00:03\n",
      "     ------------------------------- ------- 80.7/100.1 MB 8.7 MB/s eta 0:00:03\n",
      "     -------------------------------- ------ 82.3/100.1 MB 8.6 MB/s eta 0:00:03\n",
      "     -------------------------------- ------ 84.1/100.1 MB 8.6 MB/s eta 0:00:02\n",
      "     --------------------------------- ----- 86.2/100.1 MB 8.6 MB/s eta 0:00:02\n",
      "     ---------------------------------- ---- 88.1/100.1 MB 8.7 MB/s eta 0:00:02\n",
      "     ---------------------------------- ---- 89.7/100.1 MB 8.6 MB/s eta 0:00:02\n",
      "     ----------------------------------- --- 91.8/100.1 MB 8.6 MB/s eta 0:00:01\n",
      "     ------------------------------------ -- 94.1/100.1 MB 8.7 MB/s eta 0:00:01\n",
      "     ------------------------------------- - 96.2/100.1 MB 8.7 MB/s eta 0:00:01\n",
      "     --------------------------------------  98.0/100.1 MB 8.7 MB/s eta 0:00:01\n",
      "     -------------------------------------  100.1/100.1 MB 8.7 MB/s eta 0:00:01\n",
      "     -------------------------------------  100.1/100.1 MB 8.7 MB/s eta 0:00:01\n",
      "     -------------------------------------  100.1/100.1 MB 8.7 MB/s eta 0:00:01\n",
      "     -------------------------------------  100.1/100.1 MB 8.7 MB/s eta 0:00:01\n",
      "     -------------------------------------- 100.1/100.1 MB 8.2 MB/s eta 0:00:00\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Collecting Click>=6.0 (from face_recognition)\n",
      "  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)\n",
      "Collecting dlib>=19.7 (from face_recognition)\n",
      "  Downloading dlib-19.24.6.tar.gz (3.4 MB)\n",
      "     ---------------------------------------- 0.0/3.4 MB ? eta -:--:--\n",
      "     ------------------ --------------------- 1.6/3.4 MB 7.0 MB/s eta 0:00:01\n",
      "     ------------------------------- -------- 2.6/3.4 MB 6.3 MB/s eta 0:00:01\n",
      "     ---------------------------------------- 3.4/3.4 MB 5.7 MB/s eta 0:00:00\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Requirement already satisfied: numpy in c:\\users\\abish\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from face_recognition) (1.26.4)\n",
      "Requirement already satisfied: Pillow in c:\\users\\abish\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from face_recognition) (10.4.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\abish\\appdata\\local\\programs\\python\\python310\\lib\\site-packages (from Click>=6.0->face_recognition) (0.4.6)\n",
      "Downloading face_recognition-1.3.0-py2.py3-none-any.whl (15 kB)\n",
      "Downloading click-8.1.7-py3-none-any.whl (97 kB)\n",
      "Building wheels for collected packages: dlib, face-recognition-models\n",
      "  Building wheel for dlib (setup.py): started\n",
      "  Building wheel for dlib (setup.py): finished with status 'error'\n",
      "  Running setup.py clean for dlib\n",
      "  Building wheel for face-recognition-models (setup.py): started\n",
      "  Building wheel for face-recognition-models (setup.py): finished with status 'done'\n",
      "  Created wheel for face-recognition-models: filename=face_recognition_models-0.3.0-py2.py3-none-any.whl size=100566183 sha256=edb6466989ae1c543dc4dc26dafcc84f0fb236b1d3d39c36f41668fe6516a448\n",
      "  Stored in directory: c:\\users\\abish\\appdata\\local\\pip\\cache\\wheels\\7a\\eb\\cf\\e9eced74122b679557f597bb7c8e4c739cfcac526db1fd523d\n",
      "Successfully built face-recognition-models\n",
      "Failed to build dlib\n"
     ]
    },
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'face_recognition'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[1], line 13\u001b[0m\n\u001b[0;32m     11\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mcv2\u001b[39;00m\n\u001b[0;32m     12\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mmatplotlib\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mpyplot\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mplt\u001b[39;00m\n\u001b[1;32m---> 13\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mface_recognition\u001b[39;00m\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'face_recognition'"
     ]
    }
   ],
   "source": [
    "#import libraries\n",
    "!pip3 install face_recognition\n",
    "\n",
    "import torch\n",
    "import torchvision\n",
    "from torchvision import transforms\n",
    "from torch.utils.data import DataLoader\n",
    "from torch.utils.data.dataset import Dataset\n",
    "import os\n",
    "import numpy as np\n",
    "import cv2\n",
    "import matplotlib.pyplot as plt\n",
    "import face_recognition"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "27d44206-069e-4bd1-935d-8157db1dbed5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "False\n"
     ]
    },
    {
     "ename": "AssertionError",
     "evalue": "Torch not compiled with CUDA enabled",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAssertionError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[2], line 3\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mtorch\u001b[39;00m\n\u001b[0;32m      2\u001b[0m \u001b[38;5;28mprint\u001b[39m(torch\u001b[38;5;241m.\u001b[39mcuda\u001b[38;5;241m.\u001b[39mis_available())  \u001b[38;5;66;03m# Should return True if CUDA is enabled\u001b[39;00m\n\u001b[1;32m----> 3\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[43mtorch\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcuda\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcurrent_device\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m)  \u001b[38;5;66;03m# Returns the index of the current GPU\u001b[39;00m\n\u001b[0;32m      4\u001b[0m \u001b[38;5;28mprint\u001b[39m(torch\u001b[38;5;241m.\u001b[39mcuda\u001b[38;5;241m.\u001b[39mget_device_name(torch\u001b[38;5;241m.\u001b[39mcuda\u001b[38;5;241m.\u001b[39mcurrent_device()))  \u001b[38;5;66;03m# Returns the name of the GPU\u001b[39;00m\n",
      "File \u001b[1;32m~\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\torch\\cuda\\__init__.py:878\u001b[0m, in \u001b[0;36mcurrent_device\u001b[1;34m()\u001b[0m\n\u001b[0;32m    876\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mcurrent_device\u001b[39m() \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m \u001b[38;5;28mint\u001b[39m:\n\u001b[0;32m    877\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124mr\u001b[39m\u001b[38;5;124;03m\"\"\"Return the index of a currently selected device.\"\"\"\u001b[39;00m\n\u001b[1;32m--> 878\u001b[0m     \u001b[43m_lazy_init\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    879\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m torch\u001b[38;5;241m.\u001b[39m_C\u001b[38;5;241m.\u001b[39m_cuda_getDevice()\n",
      "File \u001b[1;32m~\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\torch\\cuda\\__init__.py:305\u001b[0m, in \u001b[0;36m_lazy_init\u001b[1;34m()\u001b[0m\n\u001b[0;32m    300\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mRuntimeError\u001b[39;00m(\n\u001b[0;32m    301\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mCannot re-initialize CUDA in forked subprocess. To use CUDA with \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    302\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mmultiprocessing, you must use the \u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mspawn\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m start method\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    303\u001b[0m     )\n\u001b[0;32m    304\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mhasattr\u001b[39m(torch\u001b[38;5;241m.\u001b[39m_C, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m_cuda_getDeviceCount\u001b[39m\u001b[38;5;124m\"\u001b[39m):\n\u001b[1;32m--> 305\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mAssertionError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mTorch not compiled with CUDA enabled\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m    306\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m _cudart \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m    307\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mAssertionError\u001b[39;00m(\n\u001b[0;32m    308\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mlibcudart functions unavailable. It looks like you have a broken build?\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    309\u001b[0m     )\n",
      "\u001b[1;31mAssertionError\u001b[0m: Torch not compiled with CUDA enabled"
     ]
    }
   ],
   "source": [
    "import torch\n",
    "print(torch.cuda.is_available())  # Should return True if CUDA is enabled\n",
    "print(torch.cuda.current_device())  # Returns the index of the current GPU\n",
    "print(torch.cuda.get_device_name(torch.cuda.current_device()))  # Returns the name of the GPU\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dbfa288f-09d4-4df1-9a67-f34d0a109d76",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
